### ISSUE TITLE
TODO - refactor & error handling

### ISSUE THREAD

**Issue by trys** [trys/postcss-utopia#1]
## TODO

- Consider a Typescript rewrite
- Handle malformed config better
- Refactor/split out code

**Comment by moritzlaube** [comment]
Hey @trys! I am using your postcss-utopia plugin. Thanks for authoring it! It works great. I am using it in conjunction with Tailwind. And within the app.css I am using the @utopia directive like so:

```
@layer base {
  :root {
		@utopia typeScale({
			minWidth: 320,
      maxWidth: 1280,
      minFontSize: 16,
      maxFontSize: 18,
      minTypeScale: 1.2,
      maxTypeScale: 1.25,
      positiveSteps: 5,
      negativeSteps: 2,
      prefix: "step",
  });

    @utopia spaceScale({
      minWidth: 320,
      maxWidth: 1280,
      minSize: 16,
      maxSize: 18,
      positiveSteps: [1.5, 2, 3, 4, 6, 9],
      negativeSteps: [0.75, 0.5, 0.25],
      customSizes: ["s-l"],
      prefix: "space",
  });

**Comment by trys** [comment]
@moritzlaube I think it's purely the object syntax isn't really 'valid' in CSS. I'm not sure if there's a better syntax we can follow that won't generate these errors 🤔

**Comment by shirosensei** [comment]
@trys i'm currently experiencing the same issue, is there any solution for it so far?
